name: "Deploy to Staging"

on:
  workflow_dispatch:

jobs:
  vercel:
    runs-on: ubuntu-latest
    name: "Deploy Nextjs"
    
    steps:
      - uses: actions/checkout@v2
      - uses: amondnet/vercel-action@v20
        with:
          alias-domains: "farahzaqout.dev"
          vercel-token: ${{ secrets.VERCEL_TOKEN }}
          vercel-project-id: ${{ secrets.VERCEL_PROJECT_ID }}
          vercel-org-id: ${{ secrets.VERCEL_ORG_ID }}

